### PR TITLE
Adding getCategories.py

### PR DESCRIPTION
**Pull request by pjhale**
Script that fetches both allele and gene lists.  Currently tested for sgd and wb but should work for other mods with little changes.  Will ignore entries without allele names, which was an issue for wb.

This script still requires a bit of manual variable changing but since we cant run with admin tokens yet I didn't add flags to the script or anything.  The SGD version takes a few minutes but the WB run takes hours.

I can upload the files somewhere as well.

### CODE REVIEW

**Review by valearna — APPROVED** [review]
Thanks @pjhale. The script looks good. Can you use snake case instead of camel case for the file name?

**Comment by pjhale** [comment]
Added... also added some args so that tokens wont be accidentally committed.

**Comment by valearna** [comment]
Thanks @pjhale, I meant the main script getCategories.py should be get_categories.py but your additional changes look good too.

**Comment by pjhale** [comment]
Also done... I'm planning on trying to run the full set of WB after the review.  It should all work now but we can wait to merge until then.  I only found the last problem after 1.3 million entries.

**Pull request merged**
